version: '3'

services:
  web:
    build: .
    command:
      - /bin/sh
      - -c
      - |
        python3 prototypes.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./static_site_generator:/code